from __future__ import annotations

from pathlib import Path

import pandas as pd

from log_analyzer_pro.domain.models import ReportBundle, Severity


class ExcelExporter:
    """Export analysis results into a multi-sheet Excel workbook."""

    def export(self, report: ReportBundle, destination: str) -> Path:
        output_path = Path(destination)

        summary_rows = [
            ("Files processed", report.summary.files_processed),
            ("Total entries", report.summary.total_entries),
            ("Errors", report.summary.severity_counts.get(Severity.ERROR, 0)),
            ("Warnings", report.summary.severity_counts.get(Severity.WARNING, 0)),
            ("Info", report.summary.severity_counts.get(Severity.INFO, 0)),
            ("Critical errors", report.summary.critical_count),
            ("Unique error signatures", report.summary.unique_error_count),
        ]
        summary_df = pd.DataFrame(summary_rows, columns=["Metric", "Value"])
        entries_df = pd.DataFrame(
            [
                {
                    "Timestamp": entry.timestamp,
                    "Severity": entry.severity.value,
                    "Source File": entry.source_file,
                    "Line": entry.line_number,
                    "Critical": "Yes" if entry.is_critical else "No",
                    "Message": entry.message,
                    "Normalized Message": entry.normalized_message,
                }
                for entry in report.entries
            ]
        )
        errors_df = pd.DataFrame(
            [
                {"Error Signature": signature, "Occurrences": occurrences}
                for signature, occurrences in report.summary.error_occurrences.most_common()
            ]
        )

        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            summary_df.to_excel(writer, index=False, sheet_name="Summary")
            entries_df.to_excel(writer, index=False, sheet_name="Entries")
            errors_df.to_excel(writer, index=False, sheet_name="Error Frequencies")

            for sheet_name, dataframe in {
                "Summary": summary_df,
                "Entries": entries_df,
                "Error Frequencies": errors_df,
            }.items():
                worksheet = writer.sheets[sheet_name]
                worksheet.freeze_panes = "A2"
                for column_index, column_name in enumerate(dataframe.columns, start=1):
                    max_length = max(
                        len(str(column_name)),
                        *(len(str(value)) for value in dataframe[column_name].head(200)),
                    )
                    worksheet.column_dimensions[worksheet.cell(row=1, column=column_index).column_letter].width = min(max_length + 2, 48)

            summary_sheet = writer.sheets["Summary"]
            summary_sheet["D2"] = "Generated by"
            summary_sheet["E2"] = "Log Analyzer Pro"
            summary_sheet["D3"] = "Summary Preview"
            summary_sheet["E3"] = report.summary_text

        return output_path
